pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

// Names the jar (BetterVanillaBuilding-<version>.jar). The mod ID is the lowercase form of this name
// (bettervanillabuilding), because Fabric mod IDs can't contain capital letters.
rootProject.name = 'BetterVanillaBuilding'
